name: Tag Workflow

on:
  workflow_dispatch:

env:
  a: 2
  b: 3

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ env.a > 0 && env.b > 0 }}
    steps:
      - name: Afficher les valeurs
        run: |
          echo "a = ${{ env.a }} et b = ${{ env.b }}"
